// Code generated by projectctl; DO NOT EDIT.

package projectmeta

const (
	ModuleName  = "github.com/1344812937/go-web-quick-start"
	BinaryName  = "go-web-quick-start"
	AppName     = "go-web-quick-start"
	DisplayName = "OpenAI 网关控制台"
	Description = "OpenAI 兼容的多渠道网关控制台，支持模型路由、会话亲和、失败重试、熔断、令牌和五天调用时间线。"
	Version     = "0.1.1"
	TokenPrefix = "quickstart"
	FaviconPath = "/favicon.svg"
)
