// Code generated by projectctl; DO NOT EDIT.

package projectmeta

const (
	ModuleName  = "github.com/1344812937/go-web-quick-start"
	BinaryName  = "go-web-quick-start"
	AppName     = "go-web-quick-start"
	DisplayName = "Go Web Quick Start"
	Description = "A Go and Vue 3 monorepo scaffold for rapid feature development."
	Version     = "0.1.0"
	TokenPrefix = "quickstart"
	FaviconPath = "/favicon.svg"
)
