// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/1344812937/go-web-quick-start/internal/api"
	providers2 "github.com/1344812937/go-web-quick-start/internal/api/providers"
	"github.com/1344812937/go-web-quick-start/internal/app"
	"github.com/1344812937/go-web-quick-start/internal/config"
)

// Injectors from wire.go:

func InitializeApp() *app.ApplicationHolder {
	applicationConfigManager := config.NewApplicationConfigManager()
	siteApi := api.NewSiteApi(applicationConfigManager)
	settingsApi := api.NewSettingsApi(applicationConfigManager)
	v := providers2.ProvideApis(siteApi, settingsApi)
	appWebManager := app.NewAppWebManager(applicationConfigManager, v)
	applicationHolder := app.NewApplicationHolder(applicationConfigManager, appWebManager)
	return applicationHolder
}
