// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/1344812937/go-web-quick-start/internal/api"
	providers2 "github.com/1344812937/go-web-quick-start/internal/api/providers"
	"github.com/1344812937/go-web-quick-start/internal/app"
	"github.com/1344812937/go-web-quick-start/internal/config"
	"github.com/1344812937/go-web-quick-start/internal/core/ds/providers"
	"github.com/1344812937/go-web-quick-start/internal/gateway"
)

// Injectors from wire.go:

func InitializeApp() *app.ApplicationHolder {
	applicationConfigManager := config.NewApplicationConfigManager()
	siteApi := api.NewSiteApi(applicationConfigManager)
	multiDataSource := providers.NewMultiDataSource()
	dataSource := providers.GetPrimaryDataSource(multiDataSource)
	store := gateway.NewStore(dataSource, applicationConfigManager)
	adminAuthService := gateway.NewAdminAuthService(store, applicationConfigManager)
	adminSecurity := api.NewAdminSecurity(adminAuthService, applicationConfigManager)
	settingsApi := api.NewSettingsApi(applicationConfigManager, adminSecurity)
	adminApi := api.NewAdminApi(adminAuthService, adminSecurity)
	managementService := gateway.NewManagementService(store)
	gatewayManagementApi := api.NewGatewayManagementApi(managementService, adminSecurity)
	v := providers2.ProvideApis(siteApi, settingsApi, adminApi, gatewayManagementApi)
	clientAccessService := gateway.NewClientAccessService(store)
	router := gateway.NewRouter(store, clientAccessService)
	tokenEstimator := gateway.NewTokenEstimator()
	relayService := gateway.NewRelayService(store, router, tokenEstimator, applicationConfigManager)
	openAIRelayApi := api.NewOpenAIRelayApi(clientAccessService, relayService, applicationConfigManager)
	iRootApi := providers2.ProvideRootApi(openAIRelayApi)
	appWebManager := app.NewAppWebManager(applicationConfigManager, v, iRootApi)
	applicationHolder := app.NewApplicationHolder(applicationConfigManager, appWebManager)
	return applicationHolder
}
